/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.21
 * Generated at: 2019-07-11 03:36:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import beans.ProfessorBean;
import dao.ProfessorDao;

public final class professores_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/rodapé.jsp", Long.valueOf(1562613640118L));
    _jspx_dependants.put("/topo.jsp", Long.valueOf(1562813468838L));
    _jspx_dependants.put("/mensagem.jsp", Long.valueOf(1562814904709L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("dao.ProfessorDao");
    _jspx_imports_classes.add("beans.ProfessorBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write(" \t\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Painel</title>\r\n");
      out.write("\r\n");
      out.write("\t<!-- CSS -->\r\n");
      out.write("\t<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"css/estilos.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Sessão -->\r\n");
      out.write("\t");

	
	//Obter a sessão
	Object obj = session.getAttribute("adm");
	
	//Validação
	if(obj == null){
		response.sendRedirect("index.jsp?mensagem=sessao");
	}
	
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Header -->\r\n");
      out.write("<header>\r\n");
      out.write("\t\r\n");
      out.write("\t<nav class=\"navbar fixed-top navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("  <a class=\"navbar-brand\" href=\"principal.jsp\">Colégio Ralf Lima</a>\r\n");
      out.write("  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("    <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("      <li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"calendario.jsp\">Calendario <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"alunos.jsp\">Alunos</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"professores.jsp\">Professores</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item dropdown\">\r\n");
      out.write("        <a class=\"nav-link dropdown-toggle active\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("          Perfil\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"dadosPessoais.jsp?nomeLogin=adm&senhaLogin=adm123\">Dados Pessoais</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li> \r\n");
      out.write("    </ul>\r\n");
      out.write("    <ul class=\"nav justify-content-end nav-tabs\">\r\n");
      out.write("  \t\t<li class=\"nav-item active\">\r\n");
      out.write("    \t\t<a class=\"nav-link\" id=\"batutinha\" href=\"sair.jsp\">Sair</a>\r\n");
      out.write("  \t\t</li>\r\n");
      out.write("  \t</ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\r\n");
      out.write("\t<p>Colégio Ralf Lima | Todos os direitos reservados</p>\r\n");
      out.write("\t\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- CSS -->\r\n");
      out.write("\t<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"css/estilos.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Mascara -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"css/jquery.mask.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\r\n");
      out.write("\t\tfunction limparAlerta(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdocument.getElementById(\"mensagem\").style.display = \"none\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- MENSAGEM -->\r\n");
      out.write("\t");
      out.write("<!-- MENSAGEM -->\r\n");


	// TENTATIVA
	try{
		
		String mensagem = request.getParameter("mensagem");

		switch(mensagem){
		
		// ALUNOS
		case "cadastroAlunoOk":
			out.print("<div id='mensagem' class='alert alert-success'>Aluno cadastrado com sucesso!</div>");
		break;	
		
		case "cadastroAlunoFalha":
			out.print("<div id='mensagem' class='alert alert-danger'>Falha ao cadastrar o aluno</div>");
		break;	
		
		case "excluirAlunoOk":
			out.print("<div id='mensagem' class='alert alert-success'>Produto excluido com sucesso!</div>");
		break;	
		
		case "excluirAlunoFalha":
			out.print("<div id='mensagem' class='alert alert-danger'>Falha ao excluir o aluno</div>");
		break;	
		
		case "alterarAlunoOk":
			out.print("<div id='mensagem' class='alert alert-success'>Aluno alterado com sucesso!</div>");
		break;	
		
		case "alterarAlunoFalha":
			out.print("<div id='mensagem' class='alert alert-danger'>Falha ao alterar o aluno</div>");
		break;	
		
		// PROFESSORES
		case "cadastroProfessorOk":
			out.print("<div id='mensagem' class='alert alert-success'>Professor cadastrado com sucesso!</div>");
		break;	
		
		case "cadastroProfessorFalha":
			out.print("<div id='mensagem' class='alert alert-danger'>Falha ao cadastrar o professor</div>");
		break;	
		
		case "excluirProfessorOk":
			out.print("<div id='mensagem' class='alert alert-success'>Professor excluido com sucesso!</div>");
		break;	
		
		case "excluirProfessorFalha":
			out.print("<div id='mensagem' class='alert alert-danger'>Falha ao excluir o professor</div>");
		break;	
		
		case "alterarProfessorOk":
			out.print("<div id='mensagem' class='alert alert-success'>Professor alterado com sucesso!</div>");
		break;	
		
		case "alterarProfessorFalha":
			out.print("<div id='mensagem' class='alert alert-danger'>Falha ao alterar o professor</div>");
		break;
		
		// LOGIN, SESSÃO E SAIR
		case "login":
			out.print("<div id='mensagem' class='alert alert-danger'>Usuário ou senha incorretos</div>");
		break;
		
		case "sessao":
			out.print("<div id='mensagem' class='alert alert-danger'>Sessão expirada, faça o login novamente</div>");
		break;
		
		case "sair":
			out.print("<div id='mensagem' class='alert alert-primary'>Você saiu do sistema</div>");
		break;	
		
		// DADOS PESSOAIS
		case "alterarDadosOk":
			out.print("<div id='mensagem' class='alert alert-success'>Dados alterados com sucesso</div>");
		break;
		
		case "alterarDadosFalha":
			out.print("<div id='mensagem' class='alert alert-danger'>Falha ao alterar dados</div>");
		break;
		}
	
	}catch(Exception erro){}


      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(document).ready(function(){\r\n");
      out.write("\t   \t \t$('.data').mask('00/00/0000');\r\n");
      out.write("\t   \t\t$('.cpf').mask('000.000.000-00');\r\n");
      out.write("\t   \t\t$('.tel').mask('00000-0000');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- FORMULARIO -->\r\n");
      out.write("\t");

		
		// VARIÁVEL DO cpfProfessor
		String cpfProfessor = "";
	
		// TENTATIVA DE OBTER ALUNO VIA URL
		try{
			
			cpfProfessor = request.getParameter("cpfProfessor");
			
		}catch(Exception erro){}
		
		// CONDICIONAL 
		if(cpfProfessor == null) {
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<form class=\"formularioProfessor\" action=\"requisicoes/cadastrarProfessores.jsp\" method=\"post\">\r\n");
      out.write("\t\t<input type=\"text\" class=\"cpf\" placeholder=\"CPF\" name =\"cpfProfessor\" onclick=\"limparAlerta()\">\r\n");
      out.write("\t\t<input type=\"text\" placeholder=\"Nome\" name =\"nome\" onclick=\"limparAlerta()\">\r\n");
      out.write("\t\t<input type=\"text\" placeholder=\"Senha\" name =\"senha\" onclick=\"limparAlerta()\">\r\n");
      out.write("\t\t<input type=\"text\" class=\"tel\" placeholder=\"Telefone\" name =\"telefone\" onclick=\"limparAlerta()\">\r\n");
      out.write("\t\t<input type=\"text\" class=\"data\" placeholder=\"Data de Nascimento\" name =\"data\" onclick=\"limparAlerta()\">\r\n");
      out.write("\t\t<input type=\"text\" placeholder=\"Endereço\" name =\"endereco\" onclick=\"limparAlerta()\">\r\n");
      out.write("\t\t<input type=\"email\" placeholder=\"E-mail\" name=\"email\" onclick=\"limparAlerta()\">\r\n");
      out.write("\t\t<input type=\"submit\" value=\"Cadastrar\" placeholder=\"Cadastrar\" class=\"btn btn-outline-info\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t");

		}else{
			
			// OBTER OS DADOS DO ALUNO SELECIONADO
			ProfessorDao pd = new ProfessorDao();
			ProfessorBean pb = pd.obterDados(cpfProfessor);
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<form class=\"formularioProfessor\" action=\"requisicoes/alterarProfessores.jsp\" method=\"post\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"cpf\" value=\"");
 out.print(cpfProfessor); 
      out.write("\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<input type=\"text\" class=\"cpf\" placeholder=\"CPF\" name =\"cpfProfessor\" value=\"");
 out.print(pb.getCpfProfessor()); 
      out.write("\" onclick=\"limparAlerta()\">\r\n");
      out.write("\t\t<input type=\"text\" placeholder=\"Nome\" name =\"nome\" value=\"");
 out.print(pb.getNomeProfessor()); 
      out.write("\" onclick=\"limparAlerta()\">\r\n");
      out.write("\t\t<input type=\"text\" placeholder=\"Senha\" name =\"senha\" value=\"");
 out.print(pb.getSenhaProfessor()); 
      out.write("\" onclick=\"limparAlerta()\">\r\n");
      out.write("\t\t<input type=\"text\" class=\"tel\" placeholder=\"Telefone\" name =\"telefone\" value=\"");
 out.print(pb.getTelefoneProfessor()); 
      out.write("\" onclick=\"limparAlerta()\">\r\n");
      out.write("\t\t<input type=\"text\" class=\"data\" placeholder=\"Data de Nascimento\" name =\"data\" value=\"");
 out.print(pb.getDataNascimentoProfessor()); 
      out.write("\" onclick=\"limparAlerta()\">\r\n");
      out.write("\t\t<input type=\"text\" placeholder=\"Endereço\" name =\"endereco\" value=\"");
 out.print(pb.getEnderecoProfessor()); 
      out.write("\" onclick=\"limparAlerta()\">\r\n");
      out.write("\t\t<input type=\"email\" placeholder=\"E-mail\" name=\"email\" value=\"");
 out.print(pb.getEmailProfessor()); 
      out.write("\" onclick=\"limparAlerta()\">\r\n");
      out.write("\t\t<input type=\"submit\" value=\"Alterar\" placeholder=\"Cadastrar\" class=\"btn btn-outline-info\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<a href=\"professores.jsp\">Cancelar</a>\r\n");
      out.write("\t\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- TABELA -->\r\n");
      out.write("\t");

	
		ProfessorDao pd = new ProfessorDao();
		out.print(pd.selecionar());
	
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
